deployment: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: manishk57107/loans
  tag: s14

containerPort: 8070

service:
  type: ClusterIp
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false
