deployment: configserver-deployment
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1

image:
  repository: manishk57107/configserver
  tag: s14

containerPort: 8071

service:
  type: ClusterIp
  port: 8071
  targetPort: 8071

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false
