deployment: message-deployment
serviceName: message
appLabel: message
appName: message

replicaCount: 1

image:
  repository: manishk57107/message
  tag: s14

containerPort: 9010

service:
  type: ClusterIp
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false
