server:
  port: 8071

spring:
  application:
    name: "configserver"

  profiles:
#    active: "native"   # native can be used only with file or classpath
    active: "git"

  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///D:/EazyBank"
        git:
          uri: "https://github.com/Manish0085/configserver-for-eazybank.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "Z9pH3jKxX4L6dP0uS1Bq8d9F5gN4rQmT2lVxYb+e7cA="

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG

  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"


