deployment: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 2

image:
  repository: manishk57107/accounts
  tag: s17

containerPort: 8080

service:
  type: ClusterIp
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: true
