deployment: message-deployment
serviceName: message
appLabel: message
appName: message

replicaCount: 1

image:
  repository: manishk57107/message
  tag: s17

containerPort: 9010

service:
  type: ClusterIp
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resourceserver_enabled: false
otel_enabled: false
kafka_enabled: true
