server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"

  profiles:
    active: "qa"



build:
  version: "1.3"

cards:
  message: "Welcome to EazyBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932