deployment: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: manishk57107/loans
  tag: s17

containerPort: 8090

service:
  type: ClusterIp
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false
